const SET_ALL_PRODUCTS = 'products/SET_ALL_PRODUCTS';
const SET_CURRENT_PRODUCT = 'products/SET_CURRENT_PRODUCT';
const SET_VIEW_PRODUCTS = 'products/SET_VIEW_PRODUCTS';
const SET_SEARCHED_PRODUCTS = 'products/SET_SEARCHED_PRODUCTS';
const CLEAR_VIEW_PRODUCTS = 'products/CLEAR_VIEW_PRODUCTS';

const types = {
  SET_ALL_PRODUCTS,
  SET_CURRENT_PRODUCT,
  SET_VIEW_PRODUCTS,
  SET_SEARCHED_PRODUCTS,
  CLEAR_VIEW_PRODUCTS,
};

export default types;
